# Generated by Django 4.1.1 on 2022-09-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_remove_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='activity_flag',
            field=models.BooleanField(choices=[('a', 'active'), ('i', 'inactive')], default=False, verbose_name='Активность'),
        ),
    ]
