# Generated by Django 4.1.1 on 2022-09-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_alter_comments_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentary',
            field=models.CharField(choices=[('d', 'Удалено администратором'), ('u', 'Нежелательное')], max_length=500, verbose_name='Комментарий'),
        ),
    ]
