# Generated by Django 4.1.1 on 2022-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_alter_comments_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentary',
            field=models.CharField(max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='news',
            name='activity_flag',
            field=models.CharField(choices=[('a', 'Активно'), ('i', 'Неактивно')], default='i', max_length=10, verbose_name='Активность'),
        ),
    ]
