# Generated by Django 4.1.2 on 2022-10-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Информация о пользователях', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
