# Generated by Django 4.1.1 on 2022-11-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_alter_goods_shop_storeoffers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreOffers',
            new_name='Offers',
        ),
    ]
