# Generated by Django 4.1.2 on 2022-10-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_published_news',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_flag',
        ),
    ]
