# Generated by Django 4.1.2 on 2022-10-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Обо мне'),
        ),
    ]
