# Generated by Django 4.1.2 on 2022-10-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
