# Generated by Django 4.1.1 on 2022-11-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('a', 'Новичок'), ('b', 'Продвинутый'), ('c', 'Эксперт')], default='a', max_length=100, verbose_name='Статус'),
        ),
    ]
