# Generated by Django 4.1.1 on 2022-10-06 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=36, verbose_name='Город')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('number_phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('verification_flag', models.CharField(blank=True, default='Не верифицирован', max_length=20, verbose_name='Верификация')),
                ('number_published_news', models.IntegerField(blank=True, default=0, verbose_name='Количество публикаций')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователях',
                'verbose_name_plural': 'Информация о пользователях',
                'ordering': ['user'],
                'permissions': (('can_publish', 'Может опубликовать'),),
            },
        ),
    ]
