# Generated by Django 4.1.2 on 2022-10-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'permissions': (('can_verification', 'Может верифицировать'),), 'verbose_name': 'Информация о пользователях', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
