# Generated by Django 4.1.2 on 2022-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_remove_profile_number_published_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=36, null=True, verbose_name='Обо мне'),
        ),
    ]
