# Generated by Django 4.1.1 on 2022-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0016_alter_comments_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Имя пользователя'),
        ),
    ]
