# Generated by Django 4.1.1 on 2022-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0018_alter_comments_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentary',
            field=models.TextField(max_length=500, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
