# Generated by Django 4.1.1 on 2022-09-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0021_alter_comments_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date'], 'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
