# Generated by Django 4.1.1 on 2022-09-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0022_alter_comments_options_alter_comments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Автор'),
        ),
    ]
