# Generated by Django 4.1.1 on 2022-11-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара'),
        ),
    ]
