# Generated by Django 4.1.1 on 2022-11-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0012_rename_goods_variation_product'),
        ('app_users', '0002_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.marketplace', verbose_name='Магазин'),
        ),
    ]
