# Generated by Django 4.1.1 on 2022-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_purchasehistory_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара'),
        ),
    ]
