# Generated by Django 4.1.1 on 2022-11-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0007_alter_goods_price_alter_goods_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='quantity',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='shop',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='app_marketplace.goods', verbose_name='Товар')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.price', verbose_name='Цена')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.quantity', verbose_name='Количество')),
            ],
        ),
    ]
