# Generated by Django 4.1.1 on 2022-11-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0010_alter_variation_goods_alter_variation_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='sale',
        ),
        migrations.AddField(
            model_name='variation',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Скидка в процентах'),
        ),
    ]
