# Generated by Django 4.1.1 on 2022-11-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0011_remove_goods_sale_variation_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='goods',
            new_name='product',
        ),
    ]
