# Generated by Django 4.1.1 on 2022-11-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0002_variables_remove_goods_price_goods_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='variables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_marketplace.variables', verbose_name='Переменные'),
        ),
    ]
