# Generated by Django 4.1.1 on 2022-11-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketplace', '0004_alter_variables_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='shop',
        ),
        migrations.AddField(
            model_name='variables',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_shops', to='app_marketplace.marketplace', verbose_name='Магазин'),
        ),
    ]
