# Generated by Django 4.1.1 on 2022-10-06 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date'], 'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date', 'title'], 'permissions': (('can_publish', 'Может опубликовать'),), 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentary',
            field=models.TextField(max_length=500, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='news',
            name='activity_flag',
            field=models.CharField(choices=[('a', 'Активно'), ('i', 'Неактивно')], default='i', max_length=10, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.CharField(default='', max_length=1500, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='app_news.tag'),
        ),
    ]
