# Generated by Django 4.1.1 on 2022-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisementsstatus_advertisementstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
