# Generated by Django 4.1.1 on 2022-09-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_advertisementscontactinformation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementsContactInformation',
            new_name='AdvertisementContactInformation',
        ),
        migrations.RenameModel(
            old_name='AdvertisementsStatus',
            new_name='AdvertisementStatus',
        ),
        migrations.RenameModel(
            old_name='AdvertisementsType',
            new_name='AdvertisementType',
        ),
    ]
