# Generated by Django 4.1.1 on 2022-09-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_rename_advertisementscontactinformation_advertisementcontactinformation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementStatus',
            new_name='AdvertisementsStatus',
        ),
        migrations.RenameModel(
            old_name='AdvertisementType',
            new_name='AdvertisementsType',
        ),
    ]
