# Generated by Django 4.1.1 on 2022-09-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_advertisementcontactinformation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementContactInformation',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_contact_info',
            new_name='author',
        ),
    ]
