# Generated by Django 4.1.1 on 2022-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_rename_advertisementcontactinformation_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mail',
            field=models.EmailField(default=None, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phoneNumber',
            field=models.CharField(default=None, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
