# Generated by Django 4.1.1 on 2022-09-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_alter_author_mail_alter_author_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AdvertisementAuthor',
        ),
        migrations.RenameModel(
            old_name='AdvertisementsType',
            new_name='AdvertisementStatus',
        ),
        migrations.RenameModel(
            old_name='AdvertisementsStatus',
            new_name='AdvertisementType',
        ),
    ]
