# Generated by Django 4.1.1 on 2022-09-15 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0012_rename_author_advertisementauthor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title'], 'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='advertisementauthor',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='views_count',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements.advertisementstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements.advertisementtype', verbose_name='Тип'),
        ),
    ]
