# Generated by Django 4.1.1 on 2022-09-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0013_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['created_date', 'title'], 'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements.advertisementauthor', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertisementstatus',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Статус объявления'),
        ),
        migrations.AlterField(
            model_name='advertisementtype',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Тип объявления'),
        ),
    ]
