# Generated by Django 4.1.1 on 2022-09-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0014_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementstatus',
            options={'verbose_name': 'Статус'},
        ),
    ]
