# Generated by Django 4.1.1 on 2022-09-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0015_alter_advertisementstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статус'},
        ),
        migrations.AlterModelOptions(
            name='advertisementtype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Тип'},
        ),
    ]
