# Generated by Django 4.1.1 on 2022-09-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0016_alter_advertisementstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='advertisements.advertisementcategory', verbose_name='Автор'),
        ),
    ]
