# Generated by Django 4.1.1 on 2022-09-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0017_advertisementcategory_advertisement_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementcategory',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='advertisements.advertisementcategory', verbose_name='Категории'),
        ),
    ]
