# Generated by Django 4.1.1 on 2022-09-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0018_alter_advertisementcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='price',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price_RUB',
            field=models.FloatField(default=0, verbose_name='цена_RUB'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price_USD',
            field=models.FloatField(default=0, null=True, verbose_name='цена_USD'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='advertisements.advertisementstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='advertisements.advertisementtype', verbose_name='Тип'),
        ),
    ]
